version: '3.8'
services:
  php:
    image: maklore/doctor-appointment:v1.0.2
    ports:
      - '84:80'
    environment:
      APP_ENV: production
      APP_SECRET: secret
      DATABASE_URL: "mysql://user:password@mysql.website/doctor_appointment?serverVersion=8.0.33&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      MAILER_DSN: gmail://user@gmail.com:password@default?verify_peer=0
      STRIPE_KEY: 'key'
      STRIPE_SECRET: 'secret'
      STRIPE_ENDPOINT_SECRET: 'secret'
      IS_EMAIL_VERIFICATION_REQUIRED: 'false'
      EMAIL_ADDRESS: user@gmail.com
      IMAGEKIT_PUBLIC_KEY: public
      IMAGEKIT_PRIVATE_KEY: private
      IMAGEKIT_URL: https://ik.imagekit.io/project
      IS_IMAGEKIT_ENABLED: 'true'
      IS_DOCTOR_PROFILE_APPROVED_BY_DEFAULT: 'true'
